var searchData=
[
  ['uniformfedofhandler_0',['UniformFEDofHandler',['../classlf_1_1assemble_1_1_uniform_f_e_dof_handler.html',1,'lf::assemble::UniformFEDofHandler'],['../classlf_1_1assemble_1_1_uniform_f_e_dof_handler.html#a73374ca218d3dacc6c85c68488a34649',1,'lf::assemble::UniformFEDofHandler::UniformFEDofHandler(std::shared_ptr&lt; const lf::mesh::Mesh &gt; mesh, dof_map_t dofmap, bool check_edge_orientation=true)'],['../classlf_1_1assemble_1_1_uniform_f_e_dof_handler.html#a2b6b1bc30dd3874926b7a0ddfa35a112',1,'lf::assemble::UniformFEDofHandler::UniformFEDofHandler(UniformFEDofHandler &amp;&amp;)=default'],['../classlf_1_1assemble_1_1_uniform_f_e_dof_handler.html#a9b07590a23d712ca9ba54d2d43437298',1,'lf::assemble::UniformFEDofHandler::UniformFEDofHandler(const UniformFEDofHandler &amp;)=delete']]],
  ['uniformscalarfespace_1',['UniformScalarFESpace',['../classlf_1_1uscalfe_1_1_uniform_scalar_f_e_space.html',1,'lf::uscalfe::UniformScalarFESpace&lt; SCALAR &gt;'],['../classlf_1_1uscalfe_1_1_uniform_scalar_f_e_space.html#a6a5cd720ffda613dfa9bbf84e2a20d4b',1,'lf::uscalfe::UniformScalarFESpace::UniformScalarFESpace(const UniformScalarFESpace &amp;)=delete'],['../classlf_1_1uscalfe_1_1_uniform_scalar_f_e_space.html#a8904a9624f46493bb423531bf4856fe5',1,'lf::uscalfe::UniformScalarFESpace::UniformScalarFESpace(UniformScalarFESpace &amp;&amp;) noexcept=default'],['../classlf_1_1uscalfe_1_1_uniform_scalar_f_e_space.html#a10ee03bcbeba0a9e1811e647900ac0aa',1,'lf::uscalfe::UniformScalarFESpace::UniformScalarFESpace(std::shared_ptr&lt; const lf::mesh::Mesh &gt; mesh_p, std::shared_ptr&lt; const lf::fe::ScalarReferenceFiniteElement&lt; SCALAR &gt; &gt; rfs_tria_p, std::shared_ptr&lt; const lf::fe::ScalarReferenceFiniteElement&lt; SCALAR &gt; &gt; rfs_quad_p, std::shared_ptr&lt; const lf::fe::ScalarReferenceFiniteElement&lt; SCALAR &gt; &gt; rfs_edge_p=nullptr, std::shared_ptr&lt; const lf::fe::ScalarReferenceFiniteElement&lt; SCALAR &gt; &gt; rfs_point_p=nullptr)']]],
  ['unisolvence_2',['Unisolvence',['../classlf_1_1fe_1_1_scalar_reference_finite_element.html#autotoc_md76',1,'']]],
  ['unstructured_5fgrid_3',['unstructured_grid',['../classlf_1_1io_1_1_vtk_file.html#a8130f364472456d1ceb0146ce8336b4a',1,'lf::io::VtkFile']]],
  ['unstructuredgrid_4',['UnstructuredGrid',['../classlf_1_1io_1_1_vtk_file_1_1_unstructured_grid.html',1,'lf::io::VtkFile']]],
  ['usage_5',['Usage',['../classlf_1_1mesh_1_1_entity.html#autotoc_md102',1,'Demonstration of usage'],['../group__assemble__matrix__locally.html#autotoc_md15',1,'Example Usage'],['../group__assemble__vector__locally.html#autotoc_md19',1,'Example Usage'],['../classlf_1_1fe_1_1_hierarchic_scalar_f_e_space.html#autotoc_md61',1,'Example usage'],['../classlf_1_1fe_1_1_diffusion_element_matrix_provider.html#autotoc_md65',1,'Example usage'],['../classlf_1_1fe_1_1_scalar_load_element_vector_provider.html#autotoc_md67',1,'Example usage'],['../classlf_1_1io_1_1_vtk_writer.html#autotoc_md95',1,'Example usage'],['../classlf_1_1io_1_1_vtk_writer.html#autotoc_md96',1,'Example usage'],['../classlf_1_1refinement_1_1_mesh_hierarchy.html#autotoc_md136',1,'sample usage']]],
  ['usage_20example_6',['Usage example',['../namespacelf_1_1base.html#autotoc_md39',1,'Usage example'],['../classlf_1_1base_1_1_ref_el.html#autotoc_md48',1,'Usage example'],['../classlf_1_1base_1_1_ref_el.html#autotoc_md49',1,'Usage example']]],
  ['usage_20example_3a_7',['Usage example:',['../classlf_1_1base_1_1_ref_el.html#autotoc_md43',1,'']]],
  ['usage_20of_20this_20class_8',['Usage of this class',['../classlf_1_1base_1_1_ref_el.html#autotoc_md37',1,'']]],
  ['usage_20scenarios_9',['Usage scenarios',['../conceptlf_1_1assemble_1_1_entity_matrix_provider.html#autotoc_md3',1,'Usage scenarios'],['../conceptlf_1_1assemble_1_1_entity_vector_provider.html#autotoc_md9',1,'Usage scenarios'],['../conceptlf_1_1mesh_1_1utils_1_1_mesh_function.html#autotoc_md123',1,'Usage scenarios'],['../group__entity__vector__provider.html#autotoc_md150',1,'Usage scenarios'],['../group__mesh__function.html#autotoc_md153',1,'Usage scenarios']]],
  ['usage_3a_10',['Usage:',['../classlf_1_1io_1_1_vtk_writer.html#autotoc_md93',1,'Example usage:'],['../classlf_1_1assemble_1_1_c_o_o_matrix.html#autotoc_md22',1,'sample usage:'],['../classlf_1_1io_1_1_gmsh_reader.html#autotoc_md86',1,'Sample usage:'],['../classlf_1_1io_1_1_vtk_writer.html#autotoc_md88',1,'Sample usage:']]],
  ['uscalfe_3a_3auniformscalarfespace_11',['Relation to uscalfe::UniformScalarFESpace',['../classlf_1_1fe_1_1_scalar_f_e_space.html#autotoc_md70',1,'']]],
  ['use_12',['Examples of use',['../namespacelf_1_1io.html#autotoc_md98',1,'']]],
  ['use_20a_20cutting_20edge_20version_20of_20lehrfem_13',['Use a cutting edge version of LehrFEM++',['../getting_started.html#autotoc_md167',1,'']]],
  ['use_20case_14',['Use case',['../classlf_1_1fe_1_1_mesh_function_f_e.html#autotoc_md69',1,'Use case'],['../classlf_1_1mesh_1_1_mesh.html#autotoc_md109',1,'Use case'],['../classlf_1_1mesh_1_1utils_1_1_mesh_function_global.html#autotoc_md120',1,'Use case'],['../classlf_1_1quad_1_1_quad_rule.html#autotoc_md131',1,'Use case']]],
  ['use_20lehrfem_20via_20hunter_15',['2.2. If you use LehrFEM++ via hunter',['../eigen_stacktrace_warning.html#autotoc_md162',1,'']]],
  ['user_16',['user',['../structlf_1_1base_1_1_timer_1_1cpu__times.html#a78a4717fb68118d0fa5e5826df86289e',1,'lf::base::Timer::cpu_times']]],
  ['utility_20functions_17',['Utility Functions',['../quick_reference_geometry.html#autotoc_md179',1,'']]]
];
