var namespaceprojects_1_1ipdg__stokes_1_1assemble =
[
    [ "PiecewiseBoundaryNormalJumpAssembler", "classprojects_1_1ipdg__stokes_1_1assemble_1_1_piecewise_boundary_normal_jump_assembler.html", "classprojects_1_1ipdg__stokes_1_1assemble_1_1_piecewise_boundary_normal_jump_assembler" ],
    [ "PiecewiseConstElementMatrixProvider", "classprojects_1_1ipdg__stokes_1_1assemble_1_1_piecewise_const_element_matrix_provider.html", "classprojects_1_1ipdg__stokes_1_1assemble_1_1_piecewise_const_element_matrix_provider" ],
    [ "PiecewiseConstElementVectorProvider", "classprojects_1_1ipdg__stokes_1_1assemble_1_1_piecewise_const_element_vector_provider.html", "classprojects_1_1ipdg__stokes_1_1assemble_1_1_piecewise_const_element_vector_provider" ]
];