var namespaceprojects_1_1dpg =
[
    [ "ConvectionElementMatrixProvider", "classprojects_1_1dpg_1_1_convection_element_matrix_provider.html", "classprojects_1_1dpg_1_1_convection_element_matrix_provider" ],
    [ "DiffusionElementMatrixProvider", "classprojects_1_1dpg_1_1_diffusion_element_matrix_provider.html", "classprojects_1_1dpg_1_1_diffusion_element_matrix_provider" ],
    [ "DiscontinuousScalarReferenceFiniteElement", "classprojects_1_1dpg_1_1_discontinuous_scalar_reference_finite_element.html", "classprojects_1_1dpg_1_1_discontinuous_scalar_reference_finite_element" ],
    [ "DpgElementMatrixProvider", "classprojects_1_1dpg_1_1_dpg_element_matrix_provider.html", "classprojects_1_1dpg_1_1_dpg_element_matrix_provider" ],
    [ "DpgElementVectorProvider", "classprojects_1_1dpg_1_1_dpg_element_vector_provider.html", "classprojects_1_1dpg_1_1_dpg_element_vector_provider" ],
    [ "FeDiscontinuousO0Quad", "classprojects_1_1dpg_1_1_fe_discontinuous_o0_quad.html", "classprojects_1_1dpg_1_1_fe_discontinuous_o0_quad" ],
    [ "FeDiscontinuousO0Segment", "classprojects_1_1dpg_1_1_fe_discontinuous_o0_segment.html", "classprojects_1_1dpg_1_1_fe_discontinuous_o0_segment" ],
    [ "FeDiscontinuousO0Tria", "classprojects_1_1dpg_1_1_fe_discontinuous_o0_tria.html", "classprojects_1_1dpg_1_1_fe_discontinuous_o0_tria" ],
    [ "FluxElementMatrixProvider", "classprojects_1_1dpg_1_1_flux_element_matrix_provider.html", "classprojects_1_1dpg_1_1_flux_element_matrix_provider" ],
    [ "LoadElementVectorProvider", "classprojects_1_1dpg_1_1_load_element_vector_provider.html", "classprojects_1_1dpg_1_1_load_element_vector_provider" ],
    [ "PrescribedSignProvider", "classprojects_1_1dpg_1_1_prescribed_sign_provider.html", "classprojects_1_1dpg_1_1_prescribed_sign_provider" ],
    [ "ProductElementMatrixProvider", "classprojects_1_1dpg_1_1_product_element_matrix_provider.html", "classprojects_1_1dpg_1_1_product_element_matrix_provider" ],
    [ "ProductElementMatrixProviderBuilder", "classprojects_1_1dpg_1_1_product_element_matrix_provider_builder.html", "classprojects_1_1dpg_1_1_product_element_matrix_provider_builder" ],
    [ "ProductElementVectorProvider", "classprojects_1_1dpg_1_1_product_element_vector_provider.html", "classprojects_1_1dpg_1_1_product_element_vector_provider" ],
    [ "ProductElementVectorProviderBuilder", "classprojects_1_1dpg_1_1_product_element_vector_provider_builder.html", "classprojects_1_1dpg_1_1_product_element_vector_provider_builder" ],
    [ "ProductUniformFEDofHandler", "classprojects_1_1dpg_1_1_product_uniform_f_e_dof_handler.html", "classprojects_1_1dpg_1_1_product_uniform_f_e_dof_handler" ],
    [ "ProductUniformFESpace", "classprojects_1_1dpg_1_1_product_uniform_f_e_space.html", "classprojects_1_1dpg_1_1_product_uniform_f_e_space" ],
    [ "ProductUniformFESpaceFactory", "classprojects_1_1dpg_1_1_product_uniform_f_e_space_factory.html", "classprojects_1_1dpg_1_1_product_uniform_f_e_space_factory" ],
    [ "ReactionElementMatrixProvider", "classprojects_1_1dpg_1_1_reaction_element_matrix_provider.html", "classprojects_1_1dpg_1_1_reaction_element_matrix_provider" ],
    [ "SubElementMatrixProvider", "classprojects_1_1dpg_1_1_sub_element_matrix_provider.html", "classprojects_1_1dpg_1_1_sub_element_matrix_provider" ],
    [ "SubElementVectorProvider", "classprojects_1_1dpg_1_1_sub_element_vector_provider.html", "classprojects_1_1dpg_1_1_sub_element_vector_provider" ],
    [ "TraceElementMatrixProvider", "classprojects_1_1dpg_1_1_trace_element_matrix_provider.html", "classprojects_1_1dpg_1_1_trace_element_matrix_provider" ],
    [ "TraceScalarReferenceFiniteElement", "classprojects_1_1dpg_1_1_trace_scalar_reference_finite_element.html", "classprojects_1_1dpg_1_1_trace_scalar_reference_finite_element" ]
];